services:
  - type: web
    name: student-os-backend
    env: docker
    dockerfilePath: Dockerfile
    rootDir: backend
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.mtuyjxzsrmpxdaxppnuy:tL3%40QEov1122@aws-1-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true
      - key: DIRECT_URL
        value: postgresql://postgres.mtuyjxzsrmpxdaxppnuy:tL3%40QEov1122@aws-1-ap-south-1.pooler.supabase.com:5432/postgres
      - key: JWT_SECRET
        value: super-secret-key-change-this-in-production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 3001
